### ISSUE TITLE
Add "relaxed" json support

### ISSUE THREAD

**Issue by madeso** [madeso/json#4]
All of these should be optional so we can support both relaxed and strict json.

Root JSON type
* [ ] A document with types other than object and array. #12

Comment
* [ ] Single line c-style comment #13
* [ ] Multiple line c-style comment #14
* [ ] Comment handler event?
* [ ] Comment stored in Value?

Object
* [ ] Key without quotes (limited to a sequence of confined character sets, e.g. (A-Za-z\-_)+[0-9A-Za-z\-_]* #17
* [ ] Extra comma at the end #15

Array
* [ ] Extra comma at the end #16

String
* [ ] Single quote pair #18
* [ ] String without quotes?

Number
* [ ] Fractions begins with ., e.g. .123 #19
* [ ] Number with '.' but without fraction digits, e.g. 0., 123. #20
* [ ] Hexadecimal integer, e.g. 0xDEADBEEF #21
* [ ] Infinity and NaN?

Based on https://github.com/Tencent/rapidjson/issues/36

**Comment by madeso** [comment]
Closing as there are already issues for all important points.

- Storing comments aren't useful so ignoring that.
- String without quotes already has a issue
- Infinity/nan sounds less useful and it is probably bad practice for writing it in a config file
